### PR TITLE
Fixed populateDb missing return

### PR DESCRIPTION
**Pull request by risseraka**
Fixing mistake intruduced with https://github.com/Vincit/knex-db-manager/pull/88.

### CODE REVIEW

**Comment by elhigu** [comment]
I think we can also drop node 8 support and add 14 to testing list. Now node 8 tests are still failing due to `import(...)` statement.

**Comment by risseraka** [comment]
It makes sense.
Done, waiting for the tests to complete on CI.

**Comment by risseraka** [comment]
Oops, it fails for node 14, any idea?

**Comment by risseraka** [comment]
That's really strange, I've run the tests locally using Node v14.1.0 with success.

image

**Comment by elhigu** [comment]
Retriggered tests... for some reason I don't see rerun controls in travis.

**Comment by elhigu** [comment]
CI is using node 14.8.0 that could make difference. Maybe you could also try deleting node_modules and do clean npm install + npm install knex like the CI does?

**Comment by risseraka** [comment]
Using Node v14.8.0, deleting node_modules and re-installing everything yields the same result.
I'm a bit stumped here.
image

**Comment by elhigu** [comment]
which node-pg version you have installed? looks like package.json lists in devDependecies 7.x IIRC recent knex + node 14 caused problems in that combination. Could you update pg versions in package.json?

**Comment by risseraka** [comment]
It worked! It's a miracle, ha ha.
Phew, glad it got resolved, thank you so much.

**Comment by elhigu** [comment]
Thanks! I'll publish major version today :)

**Pull request merged**
